<?php $_categories = $this->getStoreCategories() ?>
<?php if(count($_categories)): ?>
<div class="nav-container">
    <div id="custommenu">		
        <?php $level=0; foreach ($_categories as $_category): $level++; if($level == 4){ $level=1;} ?>			
            <?php echo $this->drawCustomMenuItem($_category,$level) ?>
        <?php endforeach ?>
        <div class="clearBoth"></div>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
var CUSTOMMENU_POPUP_WIDTH = 0;
var CUSTOMMENU_POPUP_TOP_OFFSET = 58;
var CUSTOMMENU_POPUP_RIGHT_OFFSET_MIN = 50;
var CUSTOMMENU_POPUP_left_OFFSET = 0;
//]]>
</script>
<?php endif ?>
